# Generated by Django 4.1.7 on 2023-04-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_category_alter_user_usertype_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="product_image/"),
        ),
    ]
