# Generated by Django 4.1.7 on 2023-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_cart_total_alter_cart_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="net_price",
            field=models.IntegerField(default=0),
        ),
    ]
