# Generated by Django 4.1.7 on 2023-05-23 04:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_cart_net_price_alter_cart_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_desc",
            field=tinymce.models.HTMLField(),
        ),
    ]
